"""The Stage 1 write-up of sim-20261008-001, generated from
stage1_focus_planes.json. Hand edits to the .md have no effect: edit this file
and re-run `python simulation_agent/src/focus_stage1.py --report`.

Every number in the text is read from the JSON, so the prose and the record
cannot disagree. What is written by hand here is only what no number holds:
the reading of the tables, the limits, and what is asked for.
"""

from __future__ import annotations

from pathlib import Path


def _g(x, n=1):
    """A number to n significant figures, for prose and tables."""
    if x is None:
        return "--"
    if x == 0:
        return "0"
    return f"{float(f'{x:.{n}g}'):g}"


def _rows(r, **match):
    return [x for x in r if all(x[k] == v for k, v in match.items())]


def report(res: dict, qdir: Path) -> None:
    (qdir / "stage1_focus_planes.md").write_text(_markdown(res), encoding="utf-8")
    _figure(res, qdir / "stage1_focus_planes.png")


def _markdown(res: dict) -> str:
    b = res["item1_bleach"]["rows"]
    dr = res["item4_drift"]["rows"]
    fp = res["item2_focus_planes"]
    wl = res["item3_wall"]
    D = res["item4_drift"]["diffusivity_um2_per_s"]
    objs = []
    for x in b:
        if x["objective"] not in objs:
            objs.append(x["objective"])

    def D_of(row, key):
        return row[key]["D_fit_over_D"]

    blurred = [D_of(x, "focused_camera_mid") for x in b if x["best_dip"] < 0.5]
    columnish = [D_of(x, "focused_camera_mid") for x in b if x["best_dip"] >= 0.9]
    all_D = [D_of(x, f"focused_camera_{p}") for x in b for p in ("coverslip", "quarter", "mid")]
    blind = [D_of(x, f"depth_blind_camera_{p}") for x in b for p in ("coverslip", "quarter", "mid")]
    focus_moves = [max(D_of(x, "focused_camera_mid"), D_of(x, "focused_camera_coverslip"))
                   / min(D_of(x, "focused_camera_mid"), D_of(x, "focused_camera_coverslip")) for x in b]
    dip_gain = [x["focused_camera_mid"]["dip"] / x["focused_camera_coverslip"]["dip"] for x in b]
    hi = [x for x in b if x["objective"] in ("40x water", "60x oil", "100x oil")
          and x["disc_radius_um"] <= 10 and x["chamber_depth_um"] >= 30]
    hi_dips = [x["best_dip"] for x in hi]
    mobile = [x["focused_camera_mid"]["mobile_fraction"] for x in b]

    L = []
    a = L.append
    a("# sim-20261008-001, Stage 1: which plane a measurement depends on, and which plane the focus search will find")
    a("")
    a("*Generated by `simulation_agent/src/report_focus.py` from `stage1_focus_planes.json`; the JSON is the record. "
      "Closed forms and exact integrals only -- no particle simulation, no rendered image, no model changed. "
      "Written by simulation-20261007-1 for task 026.*")
    a("")
    a("**Every input was read from this agent's copy of the knowledge base, not asked of the librarian, "
      "whose server did not connect in this session.** The values are the same entries; what is missing is the "
      "record that the service answered. Answers are in decades: differences under a factor of ten are ties.")
    a("")
    a("## The four answers")
    a("")
    a(f"1. **The bleached disc is a column only at low magnification, large discs or thin chambers. At 40x to 100x "
      f"a disc of 1 to 10 um in a chamber 30 um deep or more bleaches a slab a few disc radii thick, with "
      f"{_g(min(hi_dips))} to {_g(max(hi_dips))} of a column's contrast.** That overturns the bead count the earlier "
      f"bleach result gave, but not its diffusivity: the agreed fit reads D at {_g(min(all_D))} to {_g(max(all_D))} of "
      f"the true value in every case computed. That is never a factor of ten, so it is a tie, and it barely depends "
      f"on where the focus sits -- moving the focus from the coverslip to mid-chamber changes D by at most "
      f"{_g(max(focus_moves), 2)} times. **Focus mid-chamber for the contrast**, which there is up to "
      f"{_g(max(dip_gain), 2)} times the coverslip's, and hold focus to the tolerance in the table below.")
    a("2. **On the 100 nm suspension the focus search will find the coverslip, not the plane the bleach wants, "
      "unless the glass is very clean.** In a uniform suspension every plane inside the chamber looks the same to a "
      "sharpness measure, so it has no maximum there. Beads stuck to the glass make one, and only a handful per field "
      "are needed (table below). If beads stick to the top surface too, the search sees two equal peaks by "
      "construction. **For the 5 um beads the glass is not the particle plane**: they rest on it with their centres "
      f"{_g(wl['5um']['radius_um'], 2)} um up, which is more than a depth of field from 20x up.")
    h2 = wl["5um"]["parallel_heights_um"]["0.5"]
    a(f"3. **The wall slows the trapped 5 um bead's in-plane motion by a factor of 2 once its centre is below "
      f"about {_g(h2, 2)} um -- a gap of {_g(h2 - wl['5um']['radius_um'], 1)} um -- and by a factor of 10 only in "
      f"contact.** Above that the double-well timescales are a tie with the bulk model. For the 100 nm beads the "
      f"wall moves the bleach recovery by a few per cent at most.")
    rates = [x for x in dr if x["drift_rate_um_per_s_factor_2"] is not None]
    strict = min(rates, key=lambda x: x["drift_rate_um_per_s_factor_2"])
    loose = max(rates, key=lambda x: x["drift_rate_um_per_s_factor_2"])
    cam_hi = min(x["camera_tolerance_um_factor_2"] for x in rates)
    a(f"4. **A record must hold focus to about {_g(strict['drift_rate_um_per_s_factor_2'])} um/s at the strictest** "
      f"-- a {strict['disc_radius_um']} um disc at {strict['objective']}, whose record runs about "
      f"{_g(strict['record_s'])} s -- **and to about {_g(loose['drift_rate_um_per_s_factor_2'])} um/s at the most "
      f"forgiving**, a small disc at low magnification. After the bleach only the camera's focus matters, and at high "
      f"magnification it must stay within about {_g(cam_hi)} um of the bleach plane, tighter than the bleach plane "
      "itself must be placed.")
    a("")

    # ------------------------------------------------------------------ item 1
    a("## 1. The bleach is a column only sometimes")
    a("")
    a("A pattern projected through the objective is sharp only near the plane it is focused on. Away from it, each "
      "depth sees the disc blurred by a cone whose half-width grows with distance from focus, steeply at high "
      "numerical aperture. Through a chamber, the camera adds up depths bleached sharply near focus and only faintly "
      "far from it, and it sees each depth through its own blur too. Both are computed here exactly, together with "
      "the beads' diffusion in depth between the two walls, and the result is fitted the way the agreed fit does: "
      "the sharp-disc recovery, the radius taken where the first frame's dip is half its depth, a record ten recovery "
      "times long.")
    a("")
    a("**D fitted / true D, and the contrast relative to a true column**, with the pattern and the camera focused "
      "together (the projection path's relation to the camera is not in the knowledge base -- see below):")
    a("")
    a("| lens | disc (um) | chamber (um) | D, focus at glass | D, focus mid | contrast at glass | contrast mid | apparent mobile fraction |")
    a("|---|---|---|---|---|---|---|---|")
    for x in b:
        c, m = x["focused_camera_coverslip"], x["focused_camera_mid"]
        a(f"| {x['objective']} | {x['disc_radius_um']} | {x['chamber_depth_um']} | {_g(c['D_fit_over_D'], 2)} | "
          f"{_g(m['D_fit_over_D'], 2)} | {_g(c['dip'], 2)} | {_g(m['dip'], 2)} | {_g(m['mobile_fraction'], 2)} |")
    a("")
    a(f"Read it this way. **Where the contrast is near 1 the bleach is a column, and D comes out at "
      f"{_g(min(columnish), 2) if columnish else '--'} to {_g(max(columnish), 2) if columnish else '--'}.** "
      f"Where the contrast has fallen below a half, D comes out at {_g(min(blurred), 2)} to {_g(max(blurred), 2)}: "
      "the sharp core of the dip sits on a broad shallow halo from the defocused depths, the halo widens the radius "
      "the fit measures and recovers too slowly to be fitted, and the two settle at about half. **It does not go lower "
      "however blurred the pattern gets**, because a halo much wider than the disc only adds a slow background. The "
      f"same halo shows as an apparent immobile fraction of up to {_g(1 - min(mobile), 1)} where there is none.")
    a("")
    a(f"For comparison, a camera that sees every depth equally -- the earlier result's assumption -- gives "
      f"{_g(min(blind), 2)} to {_g(max(blind), 2)}. **So the depth average the earlier result used is exact for that "
      "camera**, and the camera's own depth selectivity, with beads diffusing in and out of the plane it sees, moves "
      "D by less than a factor of two. A particle simulation is not needed to settle that question.")
    a("")
    a("**What this corrects in the earlier bleach result (sim-20260930-401).** It found that one bleach places D "
      "in the right decade above about 300 beads in the disc, counting beads through the whole chamber depth. "
      "Only the bleached slab carries the signal, while every bead in the column adds noise, so the count that "
      "matters is the column's count times the contrast squared. **Where the contrast is 0.1 a curve needs about a "
      "hundred times the beads the earlier table gives, and where it is 0.01, ten thousand times.** Its timing "
      "limits and its diffusivity stand. It also named defocus as the likely cause of a soft-edged disc reading D "
      "two to four times low; computed directly, defocus gives about two, the low end of that range.")
    a("")
    a("**Where to focus, and how precisely.** The contrast is greatest with the focus mid-chamber. These are the "
      "distances the focus may sit from there before the contrast halves and before it falls tenfold, beside the "
      "lens's depth of field:")
    a("")
    a("| lens | disc (um) | chamber (um) | best contrast | halves at (um from mid) | falls tenfold at (um from mid) |")
    a("|---|---|---|---|---|---|")
    for x in b:
        a(f"| {x['objective']} | {x['disc_radius_um']} | {x['chamber_depth_um']} | {_g(x['best_dip'], 2)} | "
          f"{_g(x['focus_tolerance_um_dip_factor_2'], 2)} | {_g(x['focus_tolerance_um_dip_factor_10'], 2)} |")
    a("")
    inside = [x for x in b if x["focus_tolerance_um_dip_factor_2"] is None
              or x["focus_tolerance_um_dip_factor_2"] >= x["chamber_depth_um"] / 2]
    a(f"**In {len(inside)} of {len(b)} cases the contrast stays within a factor of 2 of its best with the focus "
      "anywhere inside the chamber, falling to about half at the glass in the worst of them.** So the bleach is forgiving of where in the chamber it is "
      "focused; what it does not forgive is a focus well outside the chamber, below the glass or above the lid.")
    a("")
    a("A dash means the contrast never fell that far with the focus anywhere from mid-chamber to three chamber "
      "depths below the glass. Distances are in the sample, not on the focus drive: the drive and the sample differ by "
      "a factor between about 0.8 and 1.3 depending on the lens, a tie.")
    a("")
    pp = [(x["focused_camera_mid"]["dip"], x["partial_pupil_0.3_mid"]["dip"],
           x["partial_pupil_0.3_mid"]["D_fit_over_D"]) for x in b]
    a(f"**If the patterning light does not fill the objective's opening** -- whether it does is not recorded -- the "
      f"cone is narrower and the bleach is more column-like. With the light filling 0.3 of the opening, mid-chamber "
      f"contrast rises by up to {_g(max(p[1] / p[0] for p in pp), 2)} times and D reads "
      f"{_g(min(p[2] for p in pp), 2)} to {_g(max(p[2] for p in pp), 2)}. The worst case is the one tabulated.")
    a("")

    # ------------------------------------------------------------------ item 2
    a("## 2. Which plane a sharpness maximum will find")
    a("")
    a(f"**The 100 nm beads fill the chamber**: their sedimentation length is about {_g(fp['gravitational_length_100nm_mm'])} mm. "
      "In a uniform suspension every plane inside the chamber holds the same number of beads in focus, and the "
      "out-of-focus ones are the same haze from everywhere, so a sharpness measure is flat across the interior and "
      "dips toward each wall, where half its depth of field is glass. **It has no maximum in the suspension**, and "
      "a search there returns a plane chosen by noise. The plane the bleach wants is mid-chamber, so even a search "
      "that lands in the suspension lands there only by chance.")
    a("")
    a("**Beads stuck to the glass make a maximum.** They are in focus together in one plane, and they hold still, "
      "while a free bead moves during the exposure and counts for less. The search finds the glass once stuck beads "
      "outnumber the free beads in focus. The number of stuck beads in a 100 um by 100 um field above which that "
      "happens:")
    a("")
    a("| lens | depth of field (um) | volume fraction 1e-6, 10 ms | 1e-5, 10 ms | 1e-4, 10 ms | 1e-4, 100 ms |")
    a("|---|---|---|---|---|---|")
    for x in fp["rows"]:
        t = x["stuck_density_threshold_per_1e4_um2"]
        a(f"| {x['objective']} | {_g(x['depth_of_field_100nm_um'], 2)} | {_g(t['1e-06']['10ms'])} | "
          f"{_g(t['1e-05']['10ms'])} | {_g(t['0.0001']['10ms'])} | {_g(t['0.0001']['100ms'])} |")
    a("")
    hiNA = [x for x in fp["rows"] if x["depth_of_field_100nm_um"] < 2]
    thick = [x["objective"] for x in fp["rows"] if x["depth_of_field_100nm_um"] >= 10]
    lo_t = min(x["stuck_density_threshold_per_1e4_um2"]["1e-06"]["10ms"] for x in hiNA)
    hi_t = max(x["stuck_density_threshold_per_1e4_um2"]["1e-06"]["10ms"] for x in hiNA)
    a(f"**From 20x up, at a volume fraction of 1e-6, {_g(lo_t)} to {_g(hi_t)} stuck beads in a 100 um field are "
      "enough**, and the number scales with the volume fraction. "
      + (f"At {', '.join(thick)} the depth of field is deeper than most chambers, so the glass and the suspension "
         "are in focus together and the question does not arise. " if thick else "")
      + "Charged 100 nm beads stick to glass readily, and how many do on this bench is not recorded. So expect the search to "
      "find the glass: then the bleach is focused at the glass, with the contrast in the first table's \"at glass\" "
      "column. To bleach mid-chamber the plan needs the chamber's depth and a move from the found plane, and that "
      "move is the microscope plan's and the person's to set, not this card's. If beads stick to the top surface as "
      "well, there are two peaks of about equal height, a chamber depth apart, which the search should be told to "
      "expect. Choosing between them is not a sharpness question.")
    a("")
    a(f"**The 5 um beads rest on the glass** (sedimentation length {_g(fp['gravitational_length_5um_um'], 1)} um), so "
      f"their centres are a radius, {_g(wl['5um']['radius_um'], 2)} um, above it. Against the depth of field that is:")
    a("")
    a("| lens | depth of field (um) | bead centre above the glass, in depths of field |")
    a("|---|---|---|")
    for x in fp["rows"]:
        a(f"| {x['objective']} | {_g(x['depth_of_field_5um_um'], 2)} | {_g(x['bead_5um_centre_above_glass_in_dofs'], 2)} |")
    a("")
    a("Below 20x the glass and the bead centres are one plane to the search. From 20x up they are distinct. **In "
      "fluorescence** the glass gives no signal unless something is stuck to it, and the search should find the bead "
      "centres. **In transmitted light** a clear bead is a lens, not a dark object. Its contrast is least at its own "
      "centre plane and greatest on either side, and it focuses light to a bright point about "
      f"{_g(fp['ball_lens_focus_from_centre_um'], 1)} um beyond its centre (polystyrene in water, as a thick ball "
      "lens). A peak-brightness measure will lock onto that point; a gradient measure sees two peaks either side of "
      "the bead. **Which light the search uses is not recorded.** It decides which of these the search returns. A "
      "trapped bead sits where the trap holds it, which is the experiment's.")
    a("")

    # ------------------------------------------------------------------ item 3
    a("## 3. The wall")
    a("")
    a("A sphere near a flat wall moves more slowly along it, and much more slowly toward it. Far from the wall the "
      "standard reflection series holds (the first correction is 9/16 of the radius over the height); within a tenth "
      "of a radius of contact the lubrication limit replaces it, and the two agree to about 8 per cent where they "
      "meet. Motion toward the wall uses the exact series.")
    a("")
    for lab, nm in (("100nm", "100 nm"), ("5um", "5 um")):
        p, q = wl[lab]["parallel_heights_um"], wl[lab]["perpendicular_heights_um"]
        r = wl[lab]["radius_um"]
        a(f"- **{nm} beads** (radius {_g(r, 2)} um): along the wall, slowed by 10 per cent below a centre height of "
          f"{_g(p['0.9'], 2)} um and halved below {_g(p['0.5'], 2)} um; slowed tenfold only in contact. Toward the "
          f"wall: 10 per cent below {_g(q['0.9'], 2)} um, halved below {_g(q['0.5'], 2)} um, tenfold below "
          f"{_g(q['0.1'], 3)} um.")
    a("")
    a("**The 100 nm beads in a chamber:**")
    a("")
    a("| chamber (um) | depth fraction slowed by more than 10 per cent | depth-averaged diffusivity / bulk |")
    a("|---|---|---|")
    for x in wl["100nm_chamber"]:
        a(f"| {x['chamber_depth_um']} | {_g(x['fraction_slower_than_0.9'], 2)} | {_g(x['depth_average_D_par_over_D0'], 2)} |")
    a("")
    a("The column's signal averages the beads over depth, and they cross the slow layers in milliseconds, so the "
      "recovery reads the depth average. That is a few per cent: a tie.")
    a("")
    a("**The trapped 5 um bead.** Residence times and transition rates in an overdamped double well scale with the "
      "drag, so the bulk model's timescales are too short by the factor in the last column:")
    a("")
    a("| centre height (um) | gap to the glass (um) | along the wall / bulk | toward the wall / bulk | timescales longer by |")
    a("|---|---|---|---|---|")
    for x in wl["5um_by_height"]:
        a(f"| {_g(x['centre_height_um'], 2)} | {_g(x['gap_um'], 2)} | {_g(x['D_par_over_D0'], 2)} | "
          f"{_g(x['D_perp_over_D0'], 2)} | {_g(x['timescale_factor'], 2)} |")
    a("")
    a(f"**A factor of 2 below a centre height of about {_g(h2, 2)} um; a factor of 10 not at any height a bead can "
      "hold off the glass.** The bead's height is the experiment's -- the trap's height, or the plane the focus search "
      "found plus a known offset -- and is not recorded. A 5 um bead left free settles to a gap of about "
      f"{_g(wl['5um_resting_gap_um'], 1)} um, where it moves along the glass at {_g(wl['5um_resting_D_par_over_D0'], 1)} "
      "of the bulk rate: a tie, but a factor of two any free-diffusion prediction for these beads leaves out.")
    a("")

    # ------------------------------------------------------------------ item 4
    a("## 4. Holding focus over the record")
    a("")
    a("The bleach is set in the few milliseconds it lasts, so the bleach plane needs only the first item's tolerance, "
      "kept from the focus search to the bleach. After it, a drifting focus changes which depths the camera sees, "
      "and at high magnification that is the tighter of the two. Computed by moving the camera's focus away from "
      "the bleach plane and fitting again, here are the offsets at which the fitted D or the contrast moves by a factor "
      "of 2, and the drift rate that would reach that offset within the shortest record the fit allows. The offsets "
      "were tried in steps of about three times (0.3, 1, 3, 10, 30, 100 um), so each tolerance is good to that step, "
      "which is inside a decade:")
    a("")
    a("| lens | disc (um) | chamber (um) | shortest record (s) | camera offset for a factor 2 (um) | drift rate to beat (um/s) |")
    a("|---|---|---|---|---|---|")
    for x in dr:
        a(f"| {x['objective']} | {x['disc_radius_um']} | {x['chamber_depth_um']} | {_g(x['record_s'], 2)} | "
          f"{_g(x['camera_tolerance_um_factor_2'], 2)} | {_g(x['drift_rate_um_per_s_factor_2'], 1)} |")
    a("")
    a(f"A dash means no offset up to {_g(max(s['camera_offset_um'] for s in dr[0]['scan']))} um moved either by a "
      f"factor of 2. Records use D of about {_g(D)} um^2/s. **How fast this bench's focus actually drifts is not "
      "recorded**; it is the microscope side's to measure. A drift rate below the last column means the record "
      "does not need its focus checked partway through.")
    a("")

    # ------------------------------------------------------------------ limits
    a("## What this assumes, and what is missing")
    a("")
    a("- **How the patterning light reaches the sample is not in the knowledge base**: which lens projects it, "
      "whether the pattern is in focus where the camera is, and how much of the lens's opening the light fills. "
      "The tables assume the pattern and the camera are focused together and the opening is full. If the pattern "
      "is focused elsewhere, focusing the camera does not focus the bleach, and the offset between the two has to "
      "be measured before the first table applies. **This is the most useful thing to find out.**")
    a("- The chamber's depth is not recorded: 10, 30 and 100 um span the likely range.")
    a("- How many beads stick to the glass, how fast the focus drifts, how high the trapped bead sits and which "
      "light the focus search uses are not recorded. Each is left as a range or a stated case above.")
    a("- The bleach is weak (the dip scales with the light). A strong bleach saturates the core and flattens the "
      "edges, which moves the fitted D somewhat further, as the earlier result's soft-edge table showed; still "
      "inside a factor of ten.")
    a("- The optics are geometric away from focus, with a Gaussian stand-in for diffraction near it, and no "
      "aberration. A dry lens or an oil lens focusing into water blurs more than this, so the high-magnification "
      "rows are if anything optimistic.")
    a("- The 100 nm beads are taken to be the supplier's nominal size and polystyrene of the other bead's density. "
      "That they are the product named is the person's statement, not a reading of the bottle.")
    a("- The wall formulas are for a smooth flat wall and a smooth sphere, and ignore charge, which keeps a real "
      "bead some tens of nanometres off the glass.")
    a("")
    a("![Stage 1](stage1_focus_planes.png)")
    a("")
    a("---")
    v = res["validation"]
    a("Checks before use: the column limit reproduces the textbook recovery to "
      f"{_g(v['column_limit_vs_soumpasis_max_abs_error'])}; a blurred disc matches the earlier result's real-space "
      f"solver to {_g(v['gaussian_disc_vs_401_solver_max_rel_error'])}; with a depth-blind camera the exact depth "
      f"solution equals the depth average to {_g(v['modes_depth_blind_vs_depth_average_max_abs_error'])}; the defocus "
      f"kernel integrates to its closed form within {_g(v['kernel_integral_vs_closed_form_max_rel_error'])}.")
    a("")
    a("References: task 026; corrects sim-20260930-401 (`stage1_closed_forms.md`, `stage2_runs.md`); observable "
      "`bleach_recovery_diffusivity`; knowledge-base snapshot kbv-b1253d99047e, read from files (the librarian's "
      f"server did not connect); interpreter {res['interpreter']['python']}, numpy {res['interpreter']['numpy']}, "
      f"scipy {res['interpreter']['scipy']}, outside the sim environment.")
    return "\n".join(L) + "\n"


def _figure(res: dict, path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    b = res["item1_bleach"]["rows"]
    objs = []
    for x in b:
        if x["objective"] not in objs:
            objs.append(x["objective"])
    colors = dict(zip(objs, plt.cm.viridis(np.linspace(0, 0.9, len(objs)))))
    fig, ax = plt.subplots(2, 2, figsize=(13, 9.5))

    a0 = ax[0, 0]
    for o in objs:
        rows = sorted(_rows(b, objective=o), key=lambda x: x["chamber_depth_um"] / x["disc_radius_um"])
        r = [x["chamber_depth_um"] / x["disc_radius_um"] for x in rows]
        a0.plot(r, [x["focused_camera_mid"]["dip"] for x in rows], "o-", color=colors[o], label=o)
        a0.plot(r, [x["focused_camera_mid"]["D_fit_over_D"] for x in rows], "s--", color=colors[o], ms=4)
    a0.set_xscale("log"); a0.set_yscale("log"); a0.set_ylim(5e-3, 1.5)
    a0.set_xlabel("chamber depth / disc radius")
    a0.set_ylabel("circles: contrast vs a true column;  squares: D fitted / true D")
    a0.set_title("Bleach focused mid-chamber, camera focused with it")
    a0.axhline(1, color="grey", lw=0.6); a0.axhline(0.1, color="red", lw=0.6, ls=":")
    a0.text(0.35, 0.11, "a factor of ten", color="red", fontsize=7)
    a0.legend(fontsize=7, loc="lower left")

    a1 = ax[0, 1]
    for o in objs:
        x = _rows(b, objective=o, disc_radius_um=3, chamber_depth_um=30)[0]
        z = np.array(x["dip_scan"]["focus_um"]); d = np.array(x["dip_scan"]["dip"])
        zz = np.concatenate([z, 30 - z[::-1]]); dd = np.concatenate([d, d[::-1]])
        a1.plot(zz, dd, color=colors[o], label=o)
    a1.axvspan(0, 30, color="lightblue", alpha=0.25)
    a1.text(1, 0.02, "chamber", fontsize=8)
    a1.set_yscale("log"); a1.set_xlim(-40, 70)
    a1.set_xlabel("bleach focus, um from the glass (negative: below it)")
    a1.set_ylabel("contrast vs a true column")
    a1.set_title("Contrast against focus: 3 um disc, 30 um chamber")
    a1.legend(fontsize=7)

    a2 = ax[1, 0]
    w = res["item3_wall"]["5um_by_height"]
    g = [x["gap_um"] / 2.5 for x in w]
    a2.plot(g, [x["D_par_over_D0"] for x in w], "o-", label="along the wall")
    a2.plot(g, [x["D_perp_over_D0"] for x in w], "s-", label="toward the wall")
    a2.axhline(0.5, color="grey", lw=0.6, ls="--"); a2.axhline(0.1, color="red", lw=0.6, ls=":")
    a2.set_xscale("log"); a2.set_yscale("log")
    a2.set_xlabel("gap to the glass / bead radius")
    a2.set_ylabel("diffusivity / bulk (timescales scale inversely)")
    a2.set_title("The wall, for any bead size (5 um: radius 2.5 um)")
    a2.legend(fontsize=8)

    a3 = ax[1, 1]
    fp = res["item2_focus_planes"]["rows"]
    phis = sorted(fp[0]["stuck_density_threshold_per_1e4_um2"], key=float)
    for x in fp:
        a3.plot([float(p) for p in phis],
                [x["stuck_density_threshold_per_1e4_um2"][p]["10ms"] for p in phis],
                "o-", color=colors[x["objective"]], label=x["objective"])
    a3.set_xscale("log"); a3.set_yscale("log")
    a3.set_xlabel("volume fraction of 100 nm beads")
    a3.set_ylabel("stuck beads per 100 x 100 um above which\nthe search finds the glass (10 ms exposure)")
    a3.set_title("When the focus search finds the coverslip")
    a3.legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
