#!/usr/bin/env python3
"""Rebuild kb/index.json.

Store maintenance, not agent behaviour: until M3 a person curates the store by
hand and runs this. The index exists so that a card citing kb:<entry_id> can be
checked against what the store actually says -- the grade a card claims to have
inherited is verified, not trusted (check 21).

kb_version is a content hash over every entry. A card pins it (check 33) so that
siblings in one fan-out all read the same knowledge, and so that rerunning a
question at the same kb_version gives the same constraints.

    python3 librarian_agent/src/kb_index.py [--check]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

KB = Path(__file__).resolve().parent.parent / "kb"


def entry_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> dict:
    entries = {}
    for p in sorted((KB / "entries").glob("*.json")):
        data = json.loads(p.read_text())
        entries[data["entry_id"]] = {
            "file": f"entries/{p.name}",
            "kind": data["kind"],
            "grade": data["grade"],
            "grade_tag": data.get("grade_tag"),
            "symbol": data.get("symbol"),
            "formula": data.get("formula"),
            "source_ref": data["source_ref"],
            "sha256": entry_digest(p),
        }
    blob = json.dumps(entries, sort_keys=True, separators=(",", ":"))
    version = "kbv-" + hashlib.sha256(blob.encode()).hexdigest()[:12]
    return {
        "schema_version": "0.1",
        "note": "Generated by librarian_agent/src/kb_index.py. Do not hand-edit: the entries are authoritative and this is their index.",
        "kb_version": version,
        "entry_count": len(entries),
        "entries": entries,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if index.json is stale instead of rewriting it")
    args = ap.parse_args(argv)
    fresh = build()
    target = KB / "index.json"
    if args.check:
        if not target.exists():
            print("index.json is missing")
            return 1
        current = json.loads(target.read_text())
        if current.get("kb_version") != fresh["kb_version"]:
            print(f"index.json is stale: {current.get('kb_version')} but entries hash to {fresh['kb_version']}")
            return 1
        print(f"index.json is current at {fresh['kb_version']} ({fresh['entry_count']} entries)")
        return 0
    target.write_text(json.dumps(fresh, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {target.name}: {fresh['kb_version']} ({fresh['entry_count']} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
